### ISSUE TITLE
Parachain can't receive message?

### ISSUE THREAD

**Issue by aurexav** [paseo-network/support#81]
strange... when i sent the message the parachains seemed stalled. Maybe the it was something with RPC... i see all good from my side as well.

Good news is that i managed to open the HRMP channel and also the asset ID 7777 was set as sufficient as requested.

In case something is not working as expected please feel free to re open the issue.

_Originally posted by @hbulgarini in https://github.com/paseo-network/support/issues/75#issuecomment-2223461452_

**Comment by acgxv** [comment]
I believe I'm experiencing the same issue as @hbulgarini.

I can send messages to the relay chain, but when I send messages to the assethub, they are not received.

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/9eee89b0-fd60-45c1-a6c8-3bfa445a6985">

**Comment by hbulgarini** [comment]
Hey! 

We have detected that the HRMP config values are much smaller than in polkadot. 

We will take a look at these numbers and update the max values for your channel so you can try again. This is the first that come into my mind that might cause the messages to not arrive to the AH.

**Comment by acgxv** [comment]
> Hey!
> 
> We have detected that the HRMP config values are much smaller than in polkadot.
> 
> We will take a look at these numbers and update the max values for your channel so you can try again. This is the first that come into my mind that might cause the messages to not arrive to the AH.

Great! Once you've done that, let me know. Thanks so much.

**Comment by al3mart** [comment]
I have closed and send the extrinsics to open the channels again, they should take effect in the coming sessions. Please, try again once they are back open and let us know if it is any different

**Comment by acgxv** [comment]
> I have closed and send the extrinsics to open the channels again, they should take effect in the coming sessions. Please, try again once they are back open and let us know if it is any different

It looks like still can not send message to AssetHub.

Will try again later.

**Comment by hbulgarini** [comment]
> It looks like still can not send message to AssetHub.

Hey @AurevoirXavier , did you have the chance to try again?

**Comment by hbulgarini** [comment]
btw, the sibling account of your parachain in the AH had 0 PAS. I suspect this was the main reason for the failure.

I have just transferred 100PAS to the 2105 account in the AH.

**Comment by hbulgarini** [comment]
I saw some messages coming from your parachain that exceeded the weights, please take into account that Paseo (and its system chains) weights are re-benchmarked to meet the Paseo HW:

https://github.com/paseo-network/paseo-action-submission/blob/main/pas/PAS-7-Hardware_specs.md

PS: I think the original issue has gone as messages are arriving to the AH. Also i confirmed it with another para that has created the foreign asset.

**Comment by al3mart** [comment]
Please, @AurevoirXavier let us know if now your issue has been fixed so we can close this :)

**Comment by jiguantong** [comment]
> I saw some messages coming from your parachain that exceeded the weights, please take into account that Paseo (and its system chains) weights are re-benchmarked to meet the Paseo HW:
> 
> https://github.com/paseo-network/paseo-action-submission/blob/main/pas/PAS-7-Hardware_specs.md
> 
> PS: I think the original issue has gone as messages are arriving to the AH. Also i confirmed it with another para that has created the foreign asset.

It still doesn't work. Could you please provide some logs about "messages coming from para2105 to AssetHubPaseo"?

**Comment by hbulgarini** [comment]
> > I saw some messages coming from your parachain that exceeded the weights, please take into account that Paseo (and its system chains) weights are re-benchmarked to meet the Paseo HW:
> > https://github.com/paseo-network/paseo-action-submission/blob/main/pas/PAS-7-Hardware_specs.md
> > PS: I think the original issue has gone as messages are arriving to the AH. Also i confirmed it with another para that has created the foreign asset.
> 
> It still doesn't work. Could you please provide some logs about "messages coming from para2105 to AssetHubPaseo"?

We need to ask the collator maintainers the logs, however i would recommend trying with chopsticks first as this issue seems to be something specific with XCM and it can be easily reproduced with it.

**Comment by jiguantong** [comment]
> We need to ask the collator maintainers the logs, however i would recommend trying with chopsticks first as this issue seems to be something specific with XCM and it can be easily reproduced with it.

Which chain do you mean by forking via chopsticks? I'm not sure if chopsticks can debug this issue. The XCM message was sent from para(2105) successfully, but was not received in AssetHub.

![image](https://github.com/user-attachments/assets/14c54fe6-8bd5-49c7-8aac-5e7dc3904c8c)

**Comment by hbulgarini** [comment]
The messages are arriving to the AH from the para 2105. Yesterday i was able to see that in the events and this is the reason why i shared the weights difference with xavier. 
Here you have the logs, but debugging flags are not turned on. I have requested to turn on the XCM log so any issue can be detected in the logs:

[ahp_20240723.log.zip](https://github.com/user-attachments/files/16346444/ahp_20240723.log.zip)

With chopsticks you can fork the whole environment and many parachains as you want and enable the XCM interactions. I found this the best way by far to debug XCM issues as the one you are having. 

Below you have an example:

`npx @acala-network/chopsticks@latest xcm --r=paseo.chopsticks.yml  --p=darwinia.yml --p=paseo.assethub.yml`

I share the chopsticks config files for paseo and the AH:

AH

```
endpoint: wss://pas-rpc.stakeworld.io/assethub
mock-signature-host: true
db: ./db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[21], { supply: 1000000000 }]]
```

Paseo

```
endpoint:
  - wss://paseo-rpc.dwellir.com
mock-signature-host: true
db: ./db.sqlite
runtime-log-level: 5

import-storage:
  Sudo:
    Key: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY # Alice
  System:
    Account:
      -
        -
          - 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
        - providers: 1
          data:
            free: 1000000000000000
```
